# Generated by Django 6.0.5 on 2026-06-02 21:06

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    accounts.validators.validate_avatar_extension,
                    accounts.validators.validate_avatar_size,
                ],
            ),
        ),
    ]
