# Generated by Django 6.0.5 on 2026-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_note_author_note_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
