# Generated by Django 6.0.5 on 2026-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_note_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
